stages:
  - train

train:
  stage: train
  image: python:3.10-slim-bullseye
  script:
    - echo "CI_PROJECT_URL $CI_PROJECT_URL"
    - echo "CI_PROJECT_PATH $CI_PROJECT_PATH"
    - echo "CI_COMMIT_BRANCH $CI_COMMIT_BRANCH"
    - echo "CI_COMMIT_BRANCH $CI_COMMIT_BRANCH"
    - echo "CI_API_V4_URL $CI_API_V4_URL"
