stages:
  - train

train:
  stage: train
  image: python:3.10-slim-bullseye
  script:
    - apt update
    - apt install git -y
    - git clone https://github.com/pyenv/pyenv.git ~/.pyenv
    - ~/.pyenv/plugins/python-build/install.sh
    - pip install mlflow
    - python run.py --tracking_uri http://192.168.1.3:5000 --experiment_name kaggle_titanic --project_uri $CI_PROJECT_URL --version $CI_COMMIT_BRANCH
