stages:
  - train

train:
  stage: train
  image: python:3.10-slim-bullseye
  script:
    - apt update
    - apt install git -y
    - git clone https://github.com/pyenv/pyenv.git ~/.pyenv
    - ~/.pyenv/plugins/python-build/install.sh
    - pip install mlflow
    - python run.py
