stages:
  - train

train:
  stage: train
  image: python:3.10-slim-bullseye
  script:
    - apt update
    - apt install -y git libgomp1
    - pip install -r requirements.txt
    - export MLFLOW_TRACKING_URI=http://192.168.1.3:5000
    - mlflow run $CI_PROJECT_URL --experiment-name kaggle_titanic --version $CI_COMMIT_SHA --env-manager local
