stages:
  - train

train:
  stage: train
  image: python:3.10-slim-bullseye
  script:
    - sudo apt-get upgrade
    - sudo apt-get install git
    - pip install mlflow
    - mlflow run $CI_PROJECT_URL
