mlflow:
  TRACKING_URI: http://192.168.1.3:5000
  EXPERIMENT_NAME: kaggle_titanic
  PROJECT_URI: http://192.168.1.3:1080/mlteam/ml-project
  VERSION: a6e972e59018abb7df390b5977a60b69c71399a7
test_size: 0.2
random_state: 42
model_name: xgb
model:
  n_estimators: 100
  max_depth: 6
  eta: 0.3
  random_state: 1
param_grid:
  kernel:
    - linear
    - rbf
  C:
    - 0.1
    - 1
    - 10
    - 100
  gamma: 
    - 0.001
    - 0.01
    - 0.1
    - 1
features:
  - Pclass
  - Sex
  - SibSp
  - Parch
target : Survived