mlflow:
  tracking_uri: http://mlflow.home
  experiment_name: kaggle_titanic
  project_uri: http://gitlab.home/mlteam/ml-project.git
  version: null

data:
  path: "./data/train.csv"

features:
  - Pclass
  - Sex
  - SibSp
  - Parch

target: Survived

test_size: 0.2
random_state: 42

model:
  name: xgb
  params:
    n_estimators: 100
    max_depth: 6
    eta: 0.3
    random_state: 1

param_grid:
  n_estimators: [50, 100, 200]
  max_depth: [3, 5, 7] 
