# Python version required to run the project.
python: "3.10.12"
# Dependencies required to build packages. This field is optional.
build_dependencies:
  - pip
  - setuptools
  - wheel==0.37.1
# Dependencies required to run the project.
dependencies:
  - mlflow==2.10
  - scikit-learn
  - numpy
  - PyYAML
  - pandas
  - lightgbm
  - xgboost
